package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * AcidenteRelacionadoAoTrabalho generated by hbm2java
 */
public class AcidenteRelacionadoAoTrabalho extends IModel<AcidenteRelacionadoAoTrabalho> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String acidenteRelacionadoAoTrabalho;

    public AcidenteRelacionadoAoTrabalho() {
    }

    public AcidenteRelacionadoAoTrabalho(String codigo, String acidenteRelacionadoAoTrabalho) {
       this.codigo = codigo;
       this.acidenteRelacionadoAoTrabalho = acidenteRelacionadoAoTrabalho;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getAcidenteRelacionadoAoTrabalho() {
        return this.acidenteRelacionadoAoTrabalho;
    }
    
    public void setAcidenteRelacionadoAoTrabalho(String acidenteRelacionadoAoTrabalho) {
        this.acidenteRelacionadoAoTrabalho = acidenteRelacionadoAoTrabalho;
    }

    @Override
    public void copyAttributesOf(AcidenteRelacionadoAoTrabalho copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


