package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0



/**
 * CadastroAgravos generated by hbm2java
 */
public class CadastroAgravos  implements java.io.Serializable {


     private CadastroAgravosId id;
     private SistemasDeInformacao sistemasDeInformacao;
     private String codigoAgravo;
     private String agravo;
     private String acumularMes;
     private String abrangencia;
     private String estado;
     private String regional;
     private String municipio;
     private String unidade;
     private String grupoIndicador;
     private String usuario;
     private String url;

    public CadastroAgravos() {
    }

	
    public CadastroAgravos(CadastroAgravosId id, SistemasDeInformacao sistemasDeInformacao, String codigoAgravo, String agravo, String acumularMes, String abrangencia, String estado, String regional, String municipio, String unidade, String grupoIndicador, String usuario) {
        this.id = id;
        this.sistemasDeInformacao = sistemasDeInformacao;
        this.codigoAgravo = codigoAgravo;
        this.agravo = agravo;
        this.acumularMes = acumularMes;
        this.abrangencia = abrangencia;
        this.estado = estado;
        this.regional = regional;
        this.municipio = municipio;
        this.unidade = unidade;
        this.grupoIndicador = grupoIndicador;
        this.usuario = usuario;
    }
    public CadastroAgravos(CadastroAgravosId id, SistemasDeInformacao sistemasDeInformacao, String codigoAgravo, String agravo, String acumularMes, String abrangencia, String estado, String regional, String municipio, String unidade, String grupoIndicador, String usuario, String url) {
       this.id = id;
       this.sistemasDeInformacao = sistemasDeInformacao;
       this.codigoAgravo = codigoAgravo;
       this.agravo = agravo;
       this.acumularMes = acumularMes;
       this.abrangencia = abrangencia;
       this.estado = estado;
       this.regional = regional;
       this.municipio = municipio;
       this.unidade = unidade;
       this.grupoIndicador = grupoIndicador;
       this.usuario = usuario;
       this.url = url;
    }
   
    public CadastroAgravosId getId() {
        return this.id;
    }
    
    public void setId(CadastroAgravosId id) {
        this.id = id;
    }
    public SistemasDeInformacao getSistemasDeInformacao() {
        return this.sistemasDeInformacao;
    }
    
    public void setSistemasDeInformacao(SistemasDeInformacao sistemasDeInformacao) {
        this.sistemasDeInformacao = sistemasDeInformacao;
    }
    public String getCodigoAgravo() {
        return this.codigoAgravo;
    }
    
    public void setCodigoAgravo(String codigoAgravo) {
        this.codigoAgravo = codigoAgravo;
    }
    public String getAgravo() {
        return this.agravo;
    }
    
    public void setAgravo(String agravo) {
        this.agravo = agravo;
    }
    public String getAcumularMes() {
        return this.acumularMes;
    }
    
    public void setAcumularMes(String acumularMes) {
        this.acumularMes = acumularMes;
    }
    public String getAbrangencia() {
        return this.abrangencia;
    }
    
    public void setAbrangencia(String abrangencia) {
        this.abrangencia = abrangencia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getRegional() {
        return this.regional;
    }
    
    public void setRegional(String regional) {
        this.regional = regional;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(String unidade) {
        this.unidade = unidade;
    }
    public String getGrupoIndicador() {
        return this.grupoIndicador;
    }
    
    public void setGrupoIndicador(String grupoIndicador) {
        this.grupoIndicador = grupoIndicador;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


