package br.com.eagravos.mobile.modelos;

import br.com.eagravos.mobile.interfaces.IModel;

// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

/**
 * CadastroAgravos generated by hbm2java
 */
public class CadastroAgravos extends IModel<CadastroAgravos> implements java.io.Serializable  {

	private int id;
	private int sistemasDeInformacaoId;
	private String codigoAgravo;
	private String agravo;
	private String acumularMes;
	private String abrangencia;
	private String estado;
	private String regional;
	private String municipio;
	private String unidade;
	private String grupoIndicador;
	private String usuario;
	private String url;

	public CadastroAgravos() {
	}

	public CadastroAgravos(int id, int sistemasDeInformacaoId,
			 String codigoAgravo,
			String agravo, String acumularMes, String abrangencia,
			String estado, String regional, String municipio, String unidade,
			String grupoIndicador, String usuario, String url) {
		super();
		this.id = id;
		this.sistemasDeInformacaoId = sistemasDeInformacaoId;
		this.codigoAgravo = codigoAgravo;
		this.agravo = agravo;
		this.acumularMes = acumularMes;
		this.abrangencia = abrangencia;
		this.estado = estado;
		this.regional = regional;
		this.municipio = municipio;
		this.unidade = unidade;
		this.grupoIndicador = grupoIndicador;
		this.usuario = usuario;
		this.url = url;
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the sistemasDeInformacaoId
	 */
	public int getSistemasDeInformacaoId() {
		return sistemasDeInformacaoId;
	}

	/**
	 * @param sistemasDeInformacaoId
	 *            the sistemasDeInformacaoId to set
	 */
	public void setSistemasDeInformacaoId(int sistemasDeInformacaoId) {
		this.sistemasDeInformacaoId = sistemasDeInformacaoId;
	}

	public String getCodigoAgravo() {
		return this.codigoAgravo;
	}

	public void setCodigoAgravo(String codigoAgravo) {
		this.codigoAgravo = codigoAgravo;
	}

	public String getAgravo() {
		return this.agravo;
	}

	public void setAgravo(String agravo) {
		this.agravo = agravo;
	}

	public String getAcumularMes() {
		return this.acumularMes;
	}

	public void setAcumularMes(String acumularMes) {
		this.acumularMes = acumularMes;
	}

	public String getAbrangencia() {
		return this.abrangencia;
	}

	public void setAbrangencia(String abrangencia) {
		this.abrangencia = abrangencia;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getRegional() {
		return this.regional;
	}

	public void setRegional(String regional) {
		this.regional = regional;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public String getUnidade() {
		return this.unidade;
	}

	public void setUnidade(String unidade) {
		this.unidade = unidade;
	}

	public String getGrupoIndicador() {
		return this.grupoIndicador;
	}

	public void setGrupoIndicador(String grupoIndicador) {
		this.grupoIndicador = grupoIndicador;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Override
	public void copyAttributesOf(CadastroAgravos copy) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void unsetAttributes() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void cleanStringWithNull() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String label() {
		// TODO Auto-generated method stub
		return null;
	}

}
