package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.HashSet;
import java.util.Set;

/**
 * Cidades generated by hbm2java
 */
public class Cidades  extends IModel<Cidades> implements java.io.Serializable {


     private Integer id;
     private Regionais regionais;
     private String cidadeNome;
     private String cidadeCodigoIbge;
     private Set instituicaoTbs = new HashSet(0);
     private Set unidadeSaudes = new HashSet(0);

    public Cidades() {
    }

	
    public Cidades(Regionais regionais) {
        this.regionais = regionais;
    }
    public Cidades(Regionais regionais, String cidadeNome, String cidadeCodigoIbge, Set instituicaoTbs, Set unidadeSaudes) {
       this.regionais = regionais;
       this.cidadeNome = cidadeNome;
       this.cidadeCodigoIbge = cidadeCodigoIbge;
       this.instituicaoTbs = instituicaoTbs;
       this.unidadeSaudes = unidadeSaudes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Regionais getRegionais() {
        return this.regionais;
    }
    
    public void setRegionais(Regionais regionais) {
        this.regionais = regionais;
    }
    public String getCidadeNome() {
        return this.cidadeNome;
    }
    
    public void setCidadeNome(String cidadeNome) {
        this.cidadeNome = cidadeNome;
    }
    public String getCidadeCodigoIbge() {
        return this.cidadeCodigoIbge;
    }
    
    public void setCidadeCodigoIbge(String cidadeCodigoIbge) {
        this.cidadeCodigoIbge = cidadeCodigoIbge;
    }
    public Set getInstituicaoTbs() {
        return this.instituicaoTbs;
    }
    
    public void setInstituicaoTbs(Set instituicaoTbs) {
        this.instituicaoTbs = instituicaoTbs;
    }
    public Set getUnidadeSaudes() {
        return this.unidadeSaudes;
    }
    
    public void setUnidadeSaudes(Set unidadeSaudes) {
        this.unidadeSaudes = unidadeSaudes;
    }

    @Override
    public void copyAttributesOf(Cidades copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


