package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * CondutorHabilitado generated by hbm2java
 */
public class CondutorHabilitado  extends IModel<CondutorHabilitado> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String condutorHabilitado;

    public CondutorHabilitado() {
    }

    public CondutorHabilitado(String codigo, String condutorHabilitado) {
       this.codigo = codigo;
       this.condutorHabilitado = condutorHabilitado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getCondutorHabilitado() {
        return this.condutorHabilitado;
    }
    
    public void setCondutorHabilitado(String condutorHabilitado) {
        this.condutorHabilitado = condutorHabilitado;
    }

    @Override
    public void copyAttributesOf(CondutorHabilitado copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


