package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * CondicoesDaVitimaAoChegarUnidade generated by hbm2java
 */
public class CondicoesDaVitimaAoChegarUnidade extends IModel<CondicoesDaVitimaAoChegarUnidade> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String condicoesDaVitimaAoChegarUnidade;

    public CondicoesDaVitimaAoChegarUnidade() {
    }

    public CondicoesDaVitimaAoChegarUnidade(String codigo, String condicoesDaVitimaAoChegarUnidade) {
       this.codigo = codigo;
       this.condicoesDaVitimaAoChegarUnidade = condicoesDaVitimaAoChegarUnidade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getCondicoesDaVitimaAoChegarUnidade() {
        return this.condicoesDaVitimaAoChegarUnidade;
    }
    
    public void setCondicoesDaVitimaAoChegarUnidade(String condicoesDaVitimaAoChegarUnidade) {
        this.condicoesDaVitimaAoChegarUnidade = condicoesDaVitimaAoChegarUnidade;
    }

    @Override
    public void copyAttributesOf(CondicoesDaVitimaAoChegarUnidade copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


