package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.HashSet;
import java.util.Set;

/**
 * DepartamentosTb generated by hbm2java
 */
public class DepartamentosTb  extends IModel<DepartamentosTb> implements java.io.Serializable {


     private Integer id;
    // private UnidadeSaude unidadeSaude;
     private String codigo;
     private String nome;
     private String responsavel;
     //private Set departamentosSetoresTbs = new HashSet(0);

    public DepartamentosTb() {
    }

	
    public DepartamentosTb(UnidadeSaude unidadeSaude, String codigo, String nome, String responsavel) {
        this.unidadeSaude = unidadeSaude;
        this.codigo = codigo;
        this.nome = nome;
        this.responsavel = responsavel;
    }
    public DepartamentosTb(UnidadeSaude unidadeSaude, String codigo, String nome, String responsavel, Set departamentosSetoresTbs) {
       this.unidadeSaude = unidadeSaude;
       this.codigo = codigo;
       this.nome = nome;
       this.responsavel = responsavel;
       this.departamentosSetoresTbs = departamentosSetoresTbs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UnidadeSaude getUnidadeSaude() {
        return this.unidadeSaude;
    }
    
    public void setUnidadeSaude(UnidadeSaude unidadeSaude) {
        this.unidadeSaude = unidadeSaude;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getResponsavel() {
        return this.responsavel;
    }
    
    public void setResponsavel(String responsavel) {
        this.responsavel = responsavel;
    }
    public Set getDepartamentosSetoresTbs() {
        return this.departamentosSetoresTbs;
    }
    
    public void setDepartamentosSetoresTbs(Set departamentosSetoresTbs) {
        this.departamentosSetoresTbs = departamentosSetoresTbs;
    }

    @Override
    public void copyAttributesOf(DepartamentosTb copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


