package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * DepartamentosSetoresTb generated by hbm2java
 */
public class DepartamentosSetoresTb extends IModel<DepartamentosSetoresTb> implements java.io.Serializable {


     private Integer id;
     //private DepartamentosTb departamentosTb;
     private String codigoSetor;
     private String nomeSetor;

    public DepartamentosSetoresTb() {
    }

    public DepartamentosSetoresTb(DepartamentosTb departamentosTb, String codigoSetor, String nomeSetor) {
       this.departamentosTb = departamentosTb;
       this.codigoSetor = codigoSetor;
       this.nomeSetor = nomeSetor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DepartamentosTb getDepartamentosTb() {
        return this.departamentosTb;
    }
    
    public void setDepartamentosTb(DepartamentosTb departamentosTb) {
        this.departamentosTb = departamentosTb;
    }
    public String getCodigoSetor() {
        return this.codigoSetor;
    }
    
    public void setCodigoSetor(String codigoSetor) {
        this.codigoSetor = codigoSetor;
    }
    public String getNomeSetor() {
        return this.nomeSetor;
    }
    
    public void setNomeSetor(String nomeSetor) {
        this.nomeSetor = nomeSetor;
    }

    @Override
    public void copyAttributesOf(DepartamentosSetoresTb copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


