package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.HashSet;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

import com.google.smsjson.JsonNull;

/**
 * Estados generated by hbm2java
 */
public class Estados  extends IModel<Estados> implements java.io.Serializable {


     private Integer id;
     private String estadoNome;
     private String estadoSigla;
     private String estadoCodigoIbge;
     //private Set regionaises = new HashSet(0);

    public Estados() {
    }

    public Estados(String estadoNome, String estadoSigla, String estadoCodigoIbge, Set regionaises) {
       this.estadoNome = estadoNome;
       this.estadoSigla = estadoSigla;
       this.estadoCodigoIbge = estadoCodigoIbge;
       this.regionaises = regionaises;
    }
   
    public Estados(JSONObject jsonObject) throws JSONException {
		if (jsonObject!=null){
			this.id=jsonObject.getInt("id");
			this.estadoNome=jsonObject.getString("estadoNome");
			this.estadoSigla=jsonObject.getString("estadoSigla");
			this.estadoCodigoIbge=jsonObject.getString("estadoCodigoIbge");
		}
	}

	public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEstadoNome() {
        return this.estadoNome;
    }
    
    public void setEstadoNome(String estadoNome) {
        this.estadoNome = estadoNome;
    }
    public String getEstadoSigla() {
        return this.estadoSigla;
    }
    
    public void setEstadoSigla(String estadoSigla) {
        this.estadoSigla = estadoSigla;
    }
    public String getEstadoCodigoIbge() {
        return this.estadoCodigoIbge;
    }
    
    public void setEstadoCodigoIbge(String estadoCodigoIbge) {
        this.estadoCodigoIbge = estadoCodigoIbge;
    }
    public Set getRegionaises() {
        return this.regionaises;
    }
    
    public void setRegionaises(Set regionaises) {
        this.regionaises = regionaises;
    }

    @Override
    public void copyAttributesOf(Estados copy) {
        this.estadoCodigoIbge=copy.estadoCodigoIbge;
        this.estadoNome=copy.estadoNome;
        this.estadoSigla=copy.estadoSigla;
        this.id=copy.id;
        this.regionaises=copy.regionaises;
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        return this.estadoNome+"-"+this.estadoSigla;
    }




}


