package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * EvolucaoDaVitimaDAO generated by hbm2java
 */
public class EvolucaoDaVitima  extends IModel<EvolucaoDaVitima> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String evolucaoDaVitima;

    public EvolucaoDaVitima() {
    }

    public EvolucaoDaVitima(String codigo, String evolucaoDaVitima) {
       this.codigo = codigo;
       this.evolucaoDaVitima = evolucaoDaVitima;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getEvolucaoDaVitima() {
        return this.evolucaoDaVitima;
    }
    
    public void setEvolucaoDaVitima(String evolucaoDaVitima) {
        this.evolucaoDaVitima = evolucaoDaVitima;
    }

    @Override
    public void copyAttributesOf(EvolucaoDaVitima copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


