package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.Date;

/**
 * FichaAcidenteIdAcidentado generated by hbm2java
 */
public class FichaAcidenteIdAcidentado  extends IModel<FichaAcidenteIdAcidentado> implements java.io.Serializable {


     private Integer id;
     private int estadoResidenciaId;
     private int regionalResidenciaId;
     private int cidadeResidenciaId;
     private String numeroRegistro;
     private String nome;
     private Date dataNascimento;
     private Integer idade;
     private String logradouro;
     private String logradouroNumero;
     private String bairro;
     private String telefones;
     private String cartaoNacionalSaude;
     private String nomeDaMae;
     private int unidadeSaudeId;
     private int grauSeveridadeAcidenteId;
     private String numeroDocumento;
     private int tipoDocumentoId;
     private int sexoId;
     private int racaCorId;
     private int ocupacaoRelacionadaSetorTransporteId;
     private int naturezaOcupacaoRelacionadaSetorTransporteId;
     private String ocupacaoNaoRelacionadaSetorTransporte;

    public FichaAcidenteIdAcidentado() {
    }

	
    public FichaAcidenteIdAcidentado(int estadoResidenciaId, int regionalResidenciaId, int cidadeResidenciaId, String numeroRegistro, String nome, String nomeDaMae, int unidadeSaudeId, int grauSeveridadeAcidenteId, int tipoDocumentoId, int sexoId, int racaCorId, int ocupacaoRelacionadaSetorTransporteId, int naturezaOcupacaoRelacionadaSetorTransporteId, String ocupacaoNaoRelacionadaSetorTransporte) {
        this.estadoResidenciaId = estadoResidenciaId;
        this.regionalResidenciaId = regionalResidenciaId;
        this.cidadeResidenciaId = cidadeResidenciaId;
        this.numeroRegistro = numeroRegistro;
        this.nome = nome;
        this.nomeDaMae = nomeDaMae;
        this.unidadeSaudeId = unidadeSaudeId;
        this.grauSeveridadeAcidenteId = grauSeveridadeAcidenteId;
        this.tipoDocumentoId = tipoDocumentoId;
        this.sexoId = sexoId;
        this.racaCorId = racaCorId;
        this.ocupacaoRelacionadaSetorTransporteId = ocupacaoRelacionadaSetorTransporteId;
        this.naturezaOcupacaoRelacionadaSetorTransporteId = naturezaOcupacaoRelacionadaSetorTransporteId;
        this.ocupacaoNaoRelacionadaSetorTransporte = ocupacaoNaoRelacionadaSetorTransporte;
    }
    public FichaAcidenteIdAcidentado(int estadoResidenciaId, int regionalResidenciaId, int cidadeResidenciaId, String numeroRegistro, String nome, Date dataNascimento, Integer idade, String logradouro, String logradouroNumero, String bairro, String telefones, String cartaoNacionalSaude, String nomeDaMae, int unidadeSaudeId, int grauSeveridadeAcidenteId, String numeroDocumento, int tipoDocumentoId, int sexoId, int racaCorId, int ocupacaoRelacionadaSetorTransporteId, int naturezaOcupacaoRelacionadaSetorTransporteId, String ocupacaoNaoRelacionadaSetorTransporte) {
       this.estadoResidenciaId = estadoResidenciaId;
       this.regionalResidenciaId = regionalResidenciaId;
       this.cidadeResidenciaId = cidadeResidenciaId;
       this.numeroRegistro = numeroRegistro;
       this.nome = nome;
       this.dataNascimento = dataNascimento;
       this.idade = idade;
       this.logradouro = logradouro;
       this.logradouroNumero = logradouroNumero;
       this.bairro = bairro;
       this.telefones = telefones;
       this.cartaoNacionalSaude = cartaoNacionalSaude;
       this.nomeDaMae = nomeDaMae;
       this.unidadeSaudeId = unidadeSaudeId;
       this.grauSeveridadeAcidenteId = grauSeveridadeAcidenteId;
       this.numeroDocumento = numeroDocumento;
       this.tipoDocumentoId = tipoDocumentoId;
       this.sexoId = sexoId;
       this.racaCorId = racaCorId;
       this.ocupacaoRelacionadaSetorTransporteId = ocupacaoRelacionadaSetorTransporteId;
       this.naturezaOcupacaoRelacionadaSetorTransporteId = naturezaOcupacaoRelacionadaSetorTransporteId;
       this.ocupacaoNaoRelacionadaSetorTransporte = ocupacaoNaoRelacionadaSetorTransporte;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getEstadoResidenciaId() {
        return this.estadoResidenciaId;
    }
    
    public void setEstadoResidenciaId(int estadoResidenciaId) {
        this.estadoResidenciaId = estadoResidenciaId;
    }
    public int getRegionalResidenciaId() {
        return this.regionalResidenciaId;
    }
    
    public void setRegionalResidenciaId(int regionalResidenciaId) {
        this.regionalResidenciaId = regionalResidenciaId;
    }
    public int getCidadeResidenciaId() {
        return this.cidadeResidenciaId;
    }
    
    public void setCidadeResidenciaId(int cidadeResidenciaId) {
        this.cidadeResidenciaId = cidadeResidenciaId;
    }
    public String getNumeroRegistro() {
        return this.numeroRegistro;
    }
    
    public void setNumeroRegistro(String numeroRegistro) {
        this.numeroRegistro = numeroRegistro;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public Integer getIdade() {
        return this.idade;
    }
    
    public void setIdade(Integer idade) {
        this.idade = idade;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getLogradouroNumero() {
        return this.logradouroNumero;
    }
    
    public void setLogradouroNumero(String logradouroNumero) {
        this.logradouroNumero = logradouroNumero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(String telefones) {
        this.telefones = telefones;
    }
    public String getCartaoNacionalSaude() {
        return this.cartaoNacionalSaude;
    }
    
    public void setCartaoNacionalSaude(String cartaoNacionalSaude) {
        this.cartaoNacionalSaude = cartaoNacionalSaude;
    }
    public String getNomeDaMae() {
        return this.nomeDaMae;
    }
    
    public void setNomeDaMae(String nomeDaMae) {
        this.nomeDaMae = nomeDaMae;
    }
    public int getUnidadeSaudeId() {
        return this.unidadeSaudeId;
    }
    
    public void setUnidadeSaudeId(int unidadeSaudeId) {
        this.unidadeSaudeId = unidadeSaudeId;
    }
    public int getGrauSeveridadeAcidenteId() {
        return this.grauSeveridadeAcidenteId;
    }
    
    public void setGrauSeveridadeAcidenteId(int grauSeveridadeAcidenteId) {
        this.grauSeveridadeAcidenteId = grauSeveridadeAcidenteId;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public int getTipoDocumentoId() {
        return this.tipoDocumentoId;
    }
    
    public void setTipoDocumentoId(int tipoDocumentoId) {
        this.tipoDocumentoId = tipoDocumentoId;
    }
    public int getSexoId() {
        return this.sexoId;
    }
    
    public void setSexoId(int sexoId) {
        this.sexoId = sexoId;
    }
    public int getRacaCorId() {
        return this.racaCorId;
    }
    
    public void setRacaCorId(int racaCorId) {
        this.racaCorId = racaCorId;
    }
    public int getOcupacaoRelacionadaSetorTransporteId() {
        return this.ocupacaoRelacionadaSetorTransporteId;
    }
    
    public void setOcupacaoRelacionadaSetorTransporteId(int ocupacaoRelacionadaSetorTransporteId) {
        this.ocupacaoRelacionadaSetorTransporteId = ocupacaoRelacionadaSetorTransporteId;
    }
    public int getNaturezaOcupacaoRelacionadaSetorTransporteId() {
        return this.naturezaOcupacaoRelacionadaSetorTransporteId;
    }
    
    public void setNaturezaOcupacaoRelacionadaSetorTransporteId(int naturezaOcupacaoRelacionadaSetorTransporteId) {
        this.naturezaOcupacaoRelacionadaSetorTransporteId = naturezaOcupacaoRelacionadaSetorTransporteId;
    }
    public String getOcupacaoNaoRelacionadaSetorTransporte() {
        return this.ocupacaoNaoRelacionadaSetorTransporte;
    }
    
    public void setOcupacaoNaoRelacionadaSetorTransporte(String ocupacaoNaoRelacionadaSetorTransporte) {
        this.ocupacaoNaoRelacionadaSetorTransporte = ocupacaoNaoRelacionadaSetorTransporte;
    }

    @Override
    public void copyAttributesOf(FichaAcidenteIdAcidentado copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


