package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.Date;

/**
 * FichaAcidenteEvolucao generated by hbm2java
 */
public class FichaAcidenteEvolucao  extends IModel<FichaAcidenteEvolucao> implements java.io.Serializable {


     private int fichaAcidenteIdAcidentadoId;
     private Date dataSaida;
     private Date horaSaida;
     private String locaTransferencia;
     private String observacoes;
     private int evolucaoDaVitimaId;

    public FichaAcidenteEvolucao() {
    }

	
    public FichaAcidenteEvolucao(int fichaAcidenteIdAcidentadoId, Date dataSaida, Date horaSaida, String locaTransferencia, int evolucaoDaVitimaId) {
        this.fichaAcidenteIdAcidentadoId = fichaAcidenteIdAcidentadoId;
        this.dataSaida = dataSaida;
        this.horaSaida = horaSaida;
        this.locaTransferencia = locaTransferencia;
        this.evolucaoDaVitimaId = evolucaoDaVitimaId;
    }
    public FichaAcidenteEvolucao(int fichaAcidenteIdAcidentadoId, Date dataSaida, Date horaSaida, String locaTransferencia, String observacoes, int evolucaoDaVitimaId) {
       this.fichaAcidenteIdAcidentadoId = fichaAcidenteIdAcidentadoId;
       this.dataSaida = dataSaida;
       this.horaSaida = horaSaida;
       this.locaTransferencia = locaTransferencia;
       this.observacoes = observacoes;
       this.evolucaoDaVitimaId = evolucaoDaVitimaId;
    }
   
    public int getFichaAcidenteIdAcidentadoId() {
        return this.fichaAcidenteIdAcidentadoId;
    }
    
    public void setFichaAcidenteIdAcidentadoId(int fichaAcidenteIdAcidentadoId) {
        this.fichaAcidenteIdAcidentadoId = fichaAcidenteIdAcidentadoId;
    }
    public Date getDataSaida() {
        return this.dataSaida;
    }
    
    public void setDataSaida(Date dataSaida) {
        this.dataSaida = dataSaida;
    }
    public Date getHoraSaida() {
        return this.horaSaida;
    }
    
    public void setHoraSaida(Date horaSaida) {
        this.horaSaida = horaSaida;
    }
    public String getLocaTransferencia() {
        return this.locaTransferencia;
    }
    
    public void setLocaTransferencia(String locaTransferencia) {
        this.locaTransferencia = locaTransferencia;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public int getEvolucaoDaVitimaId() {
        return this.evolucaoDaVitimaId;
    }
    
    public void setEvolucaoDaVitimaId(int evolucaoDaVitimaId) {
        this.evolucaoDaVitimaId = evolucaoDaVitimaId;
    }

    @Override
    public void copyAttributesOf(FichaAcidenteEvolucao copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


