package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.Date;

/**
 * FichaAcidenteIdLocalAtendimento generated by hbm2java
 */
public class FichaAcidenteIdLocalAtendimento  extends IModel<FichaAcidenteIdLocalAtendimento> implements java.io.Serializable {


	
     private String numeroRegistro;
     private int cidadeNotificacaoId;
     private String numeroNotificacao;
     private String numeroRegulacao;
     private Date dataAtendimento;
     private Date horaAtendimento;
     private Date dataDigitacao;
     private int unidadeSaudeId;
     private int condicaoVitimaChegadaUnidadeId;
     private int contatoId;

    public FichaAcidenteIdLocalAtendimento() {
    }

	
    public FichaAcidenteIdLocalAtendimento(String numeroRegistro, int cidadeNotificacaoId, Date dataAtendimento, Date horaAtendimento, Date dataDigitacao, int unidadeSaudeId, int condicaoVitimaChegadaUnidadeId, int contatoId) {
        this.numeroRegistro = numeroRegistro;
        this.cidadeNotificacaoId = cidadeNotificacaoId;
        this.dataAtendimento = dataAtendimento;
        this.horaAtendimento = horaAtendimento;
        this.dataDigitacao = dataDigitacao;
        this.unidadeSaudeId = unidadeSaudeId;
        this.condicaoVitimaChegadaUnidadeId = condicaoVitimaChegadaUnidadeId;
        this.contatoId = contatoId;
    }
    public FichaAcidenteIdLocalAtendimento(String numeroRegistro, int cidadeNotificacaoId, String numeroNotificacao, String numeroRegulacao, Date dataAtendimento, Date horaAtendimento, Date dataDigitacao, int unidadeSaudeId, int condicaoVitimaChegadaUnidadeId, int contatoId) {
       this.numeroRegistro = numeroRegistro;
       this.cidadeNotificacaoId = cidadeNotificacaoId;
       this.numeroNotificacao = numeroNotificacao;
       this.numeroRegulacao = numeroRegulacao;
       this.dataAtendimento = dataAtendimento;
       this.horaAtendimento = horaAtendimento;
       this.dataDigitacao = dataDigitacao;
       this.unidadeSaudeId = unidadeSaudeId;
       this.condicaoVitimaChegadaUnidadeId = condicaoVitimaChegadaUnidadeId;
       this.contatoId = contatoId;
    }
   
    public String getNumeroRegistro() {
        return this.numeroRegistro;
    }
    
    public void setNumeroRegistro(String numeroRegistro) {
        this.numeroRegistro = numeroRegistro;
    }
    public int getCidadeNotificacaoId() {
        return this.cidadeNotificacaoId;
    }
    
    public void setCidadeNotificacaoId(int cidadeNotificacaoId) {
        this.cidadeNotificacaoId = cidadeNotificacaoId;
    }
    public String getNumeroNotificacao() {
        return this.numeroNotificacao;
    }
    
    public void setNumeroNotificacao(String numeroNotificacao) {
        this.numeroNotificacao = numeroNotificacao;
    }
    public String getNumeroRegulacao() {
        return this.numeroRegulacao;
    }
    
    public void setNumeroRegulacao(String numeroRegulacao) {
        this.numeroRegulacao = numeroRegulacao;
    }
    public Date getDataAtendimento() {
        return this.dataAtendimento;
    }
    
    public void setDataAtendimento(Date dataAtendimento) {
        this.dataAtendimento = dataAtendimento;
    }
    public Date getHoraAtendimento() {
        return this.horaAtendimento;
    }
    
    public void setHoraAtendimento(Date horaAtendimento) {
        this.horaAtendimento = horaAtendimento;
    }
    public Date getDataDigitacao() {
        return this.dataDigitacao;
    }
    
    public void setDataDigitacao(Date dataDigitacao) {
        this.dataDigitacao = dataDigitacao;
    }
    public int getUnidadeSaudeId() {
        return this.unidadeSaudeId;
    }
    
    public void setUnidadeSaudeId(int unidadeSaudeId) {
        this.unidadeSaudeId = unidadeSaudeId;
    }
    public int getCondicaoVitimaChegadaUnidadeId() {
        return this.condicaoVitimaChegadaUnidadeId;
    }
    
    public void setCondicaoVitimaChegadaUnidadeId(int condicaoVitimaChegadaUnidadeId) {
        this.condicaoVitimaChegadaUnidadeId = condicaoVitimaChegadaUnidadeId;
    }
    public int getContatoId() {
        return this.contatoId;
    }
    
    public void setContatoId(int contatoId) {
        this.contatoId = contatoId;
    }

    @Override
    public void copyAttributesOf(FichaAcidenteIdLocalAtendimento copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


