package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * FichaAcidenteFatoresRelacionados generated by hbm2java
 */
public class FichaAcidenteFatoresRelacionados  extends IModel<FichaAcidenteFatoresRelacionados> implements java.io.Serializable {


     private int fichaAcidenteIdAcidentadoId;
     private int condutorHabilitadoId;
     private int usoCelularId;
     private int excessoVelocidadeId;
     private int usoCintoSegurancaId;
     private int usoCapaceteId;
     private int sonoFadigaId;
     private int usoDeBebidaAlcoolicaId;

    public FichaAcidenteFatoresRelacionados() {
    }

    public FichaAcidenteFatoresRelacionados(int fichaAcidenteIdAcidentadoId, int condutorHabilitadoId, int usoCelularId, int excessoVelocidadeId, int usoCintoSegurancaId, int usoCapaceteId, int sonoFadigaId, int usoDeBebidaAlcoolicaId) {
       this.fichaAcidenteIdAcidentadoId = fichaAcidenteIdAcidentadoId;
       this.condutorHabilitadoId = condutorHabilitadoId;
       this.usoCelularId = usoCelularId;
       this.excessoVelocidadeId = excessoVelocidadeId;
       this.usoCintoSegurancaId = usoCintoSegurancaId;
       this.usoCapaceteId = usoCapaceteId;
       this.sonoFadigaId = sonoFadigaId;
       this.usoDeBebidaAlcoolicaId = usoDeBebidaAlcoolicaId;
    }
   
    public int getFichaAcidenteIdAcidentadoId() {
        return this.fichaAcidenteIdAcidentadoId;
    }
    
    public void setFichaAcidenteIdAcidentadoId(int fichaAcidenteIdAcidentadoId) {
        this.fichaAcidenteIdAcidentadoId = fichaAcidenteIdAcidentadoId;
    }
    public int getCondutorHabilitadoId() {
        return this.condutorHabilitadoId;
    }
    
    public void setCondutorHabilitadoId(int condutorHabilitadoId) {
        this.condutorHabilitadoId = condutorHabilitadoId;
    }
    public int getUsoCelularId() {
        return this.usoCelularId;
    }
    
    public void setUsoCelularId(int usoCelularId) {
        this.usoCelularId = usoCelularId;
    }
    public int getExcessoVelocidadeId() {
        return this.excessoVelocidadeId;
    }
    
    public void setExcessoVelocidadeId(int excessoVelocidadeId) {
        this.excessoVelocidadeId = excessoVelocidadeId;
    }
    public int getUsoCintoSegurancaId() {
        return this.usoCintoSegurancaId;
    }
    
    public void setUsoCintoSegurancaId(int usoCintoSegurancaId) {
        this.usoCintoSegurancaId = usoCintoSegurancaId;
    }
    public int getUsoCapaceteId() {
        return this.usoCapaceteId;
    }
    
    public void setUsoCapaceteId(int usoCapaceteId) {
        this.usoCapaceteId = usoCapaceteId;
    }
    public int getSonoFadigaId() {
        return this.sonoFadigaId;
    }
    
    public void setSonoFadigaId(int sonoFadigaId) {
        this.sonoFadigaId = sonoFadigaId;
    }
    public int getUsoDeBebidaAlcoolicaId() {
        return this.usoDeBebidaAlcoolicaId;
    }
    
    public void setUsoDeBebidaAlcoolicaId(int usoDeBebidaAlcoolicaId) {
        this.usoDeBebidaAlcoolicaId = usoDeBebidaAlcoolicaId;
    }

    @Override
    public void copyAttributesOf(FichaAcidenteFatoresRelacionados copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


