package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * NaturezaOcupacaoRelacionadaSetorTransporte generated by hbm2java
 */
public class NaturezaOcupacaoRelacionadaSetorTransporte  extends IModel<NaturezaOcupacaoRelacionadaSetorTransporte> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String naturezaRelacionada;

    public NaturezaOcupacaoRelacionadaSetorTransporte() {
    }

    public NaturezaOcupacaoRelacionadaSetorTransporte(String codigo, String naturezaRelacionada) {
       this.codigo = codigo;
       this.naturezaRelacionada = naturezaRelacionada;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNaturezaRelacionada() {
        return this.naturezaRelacionada;
    }
    
    public void setNaturezaRelacionada(String naturezaRelacionada) {
        this.naturezaRelacionada = naturezaRelacionada;
    }

    @Override
    public void copyAttributesOf(NaturezaOcupacaoRelacionadaSetorTransporte copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


