package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import org.json.JSONException;
import org.json.JSONObject;

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * OcupacaoRelacionadaSetorTransporteWebService generated by hbm2java
 */
public class OcupacaoRelacionadaSetorTransporte  extends IModel<OcupacaoRelacionadaSetorTransporte> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String ocupacaoRelacionadaSetorTransporte;

    public OcupacaoRelacionadaSetorTransporte() {
    }

    public OcupacaoRelacionadaSetorTransporte(String codigo, String ocupacaoRelacionadaSetorTransporte) {
       this.codigo = codigo;
       this.ocupacaoRelacionadaSetorTransporte = ocupacaoRelacionadaSetorTransporte;
    }
   
    public OcupacaoRelacionadaSetorTransporte(JSONObject jsonObject) throws JSONException {
		if (jsonObject!= null){
			this.codigo=jsonObject.getString("codigo");
			this.id=jsonObject.getInt("id");
			
			this.ocupacaoRelacionadaSetorTransporte=jsonObject.getString("ocupacaoRelacionadaSetorTransporte");
		}
	}

	public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getOcupacaoRelacionadaSetorTransporte() {
        return this.ocupacaoRelacionadaSetorTransporte;
    }
    
    public void setOcupacaoRelacionadaSetorTransporte(String ocupacaoRelacionadaSetorTransporte) {
        this.ocupacaoRelacionadaSetorTransporte = ocupacaoRelacionadaSetorTransporte;
    }

    @Override
    public void copyAttributesOf(OcupacaoRelacionadaSetorTransporte copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


