package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * OutroFatorRelacionadoAoAcidente generated by hbm2java
 */
public class OutroFatorRelacionadoAoAcidente  extends IModel<OutroFatorRelacionadoAoAcidente> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String outroFatorRelacionadoAoAcidente;

    public OutroFatorRelacionadoAoAcidente() {
    }

	
    public OutroFatorRelacionadoAoAcidente(String codigo) {
        this.codigo = codigo;
    }
    public OutroFatorRelacionadoAoAcidente(String codigo, String outroFatorRelacionadoAoAcidente) {
       this.codigo = codigo;
       this.outroFatorRelacionadoAoAcidente = outroFatorRelacionadoAoAcidente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getOutroFatorRelacionadoAoAcidente() {
        return this.outroFatorRelacionadoAoAcidente;
    }
    
    public void setOutroFatorRelacionadoAoAcidente(String outroFatorRelacionadoAoAcidente) {
        this.outroFatorRelacionadoAoAcidente = outroFatorRelacionadoAoAcidente;
    }

    @Override
    public void copyAttributesOf(OutroFatorRelacionadoAoAcidente copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


