package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * RacaCor generated by hbm2java
 */
public class RacaCor  extends IModel<RacaCor> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String racaCor;

    public RacaCor() {
    }

    public RacaCor(String codigo, String racaCor) {
       this.codigo = codigo;
       this.racaCor = racaCor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getRacaCor() {
        return this.racaCor;
    }
    
    public void setRacaCor(String racaCor) {
        this.racaCor = racaCor;
    }

    @Override
    public void copyAttributesOf(RacaCor copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


