package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.HashSet;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

/**
 * Regionais generated by hbm2java
 */
public class Regionais  extends IModel<Regionais> implements java.io.Serializable {


     private Integer id;
     private String regionalNome;
     private String regionalCodigoIbge;
     private Integer estadoId;

    public Regionais() {
    }

	

   
    public Regionais(JSONObject jsonObject) throws JSONException {
		if (jsonObject!= null){
			this.id=jsonObject.getInt("id");
			this.regionalCodigoIbge=jsonObject.getString("regionalCodigoIbge");
			this.regionalNome=jsonObject.getString("regionalNome");
			this.estadoId=jsonObject.getInt("estadoId");
		}
	}


	

	/**
	 * @return the estadoId
	 */
	public Integer getEstadoId() {
		return estadoId;
	}




	/**
	 * @param estadoId the estadoId to set
	 */
	public void setEstadoId(Integer estadoId) {
		this.estadoId = estadoId;
	}




	public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getRegionalNome() {
        return this.regionalNome;
    }
    
    public void setRegionalNome(String regionalNome) {
        this.regionalNome = regionalNome;
    }
    public String getRegionalCodigoIbge() {
        return this.regionalCodigoIbge;
    }
    
    public void setRegionalCodigoIbge(String regionalCodigoIbge) {
        this.regionalCodigoIbge = regionalCodigoIbge;
    }


    @Override
    public void copyAttributesOf(Regionais copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


