package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.HashSet;
import java.util.Set;

/**
 * Regionais generated by hbm2java
 */
public class Regionais  extends IModel<Regionais> implements java.io.Serializable {


     private Integer id;
     private Estados estados;
     private String regionalNome;
     private String regionalCodigoIbge;
     private Set cidadeses = new HashSet(0);

    public Regionais() {
    }

	
    public Regionais(Estados estados) {
        this.estados = estados;
    }
    public Regionais(Estados estados, String regionalNome, String regionalCodigoIbge, Set cidadeses) {
       this.estados = estados;
       this.regionalNome = regionalNome;
       this.regionalCodigoIbge = regionalCodigoIbge;
       this.cidadeses = cidadeses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    public String getRegionalNome() {
        return this.regionalNome;
    }
    
    public void setRegionalNome(String regionalNome) {
        this.regionalNome = regionalNome;
    }
    public String getRegionalCodigoIbge() {
        return this.regionalCodigoIbge;
    }
    
    public void setRegionalCodigoIbge(String regionalCodigoIbge) {
        this.regionalCodigoIbge = regionalCodigoIbge;
    }
    public Set getCidadeses() {
        return this.cidadeses;
    }
    
    public void setCidadeses(Set cidadeses) {
        this.cidadeses = cidadeses;
    }

    @Override
    public void copyAttributesOf(Regionais copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


