package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.HashSet;
import java.util.Set;

/**
 * SistemasDeInformacao generated by hbm2java
 */
public class SistemasDeInformacao  extends IModel<SistemasDeInformacao> implements java.io.Serializable {


     private Integer id;
     private String nomeDoSistema;
     private String descricao;
     private Set cadastroAgravoses = new HashSet(0);

    public SistemasDeInformacao() {
    }

    public SistemasDeInformacao(String nomeDoSistema, String descricao, Set cadastroAgravoses) {
       this.nomeDoSistema = nomeDoSistema;
       this.descricao = descricao;
       this.cadastroAgravoses = cadastroAgravoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomeDoSistema() {
        return this.nomeDoSistema;
    }
    
    public void setNomeDoSistema(String nomeDoSistema) {
        this.nomeDoSistema = nomeDoSistema;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getCadastroAgravoses() {
        return this.cadastroAgravoses;
    }
    
    public void setCadastroAgravoses(Set cadastroAgravoses) {
        this.cadastroAgravoses = cadastroAgravoses;
    }

   
    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void copyAttributesOf(SistemasDeInformacao copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


