package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * SonoFadiga generated by hbm2java
 */
public class SonoFadiga  extends IModel<SonoFadiga> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String sonoFadiga;

    public SonoFadiga() {
    }

    public SonoFadiga(String codigo, String sonoFadiga) {
       this.codigo = codigo;
       this.sonoFadiga = sonoFadiga;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getSonoFadiga() {
        return this.sonoFadiga;
    }
    
    public void setSonoFadiga(String sonoFadiga) {
        this.sonoFadiga = sonoFadiga;
    }

    @Override
    public void copyAttributesOf(SonoFadiga copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


