package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0


import br.com.eagravos.mobile.interfaces.IModel;
import java.util.HashSet;
import java.util.Set;

/**
 * UnidadeSaude generated by hbm2java
 */
public class UnidadeSaude  extends IModel<UnidadeSaude> implements java.io.Serializable {


     private Integer id;
     //private TiposUnidade tiposUnidade;
     //private Cidades cidades;
     private String numeroCnes;
     private String nomeDaUnidade;
     private String tipoUnidade;
     //private Set departamentosTbs = new HashSet(0);

    public UnidadeSaude() {
    }

	
    public UnidadeSaude(TiposUnidade tiposUnidade, Cidades cidades, String numeroCnes, String nomeDaUnidade, String tipoUnidade) {
        this.tiposUnidade = tiposUnidade;
        this.cidades = cidades;
        this.numeroCnes = numeroCnes;
        this.nomeDaUnidade = nomeDaUnidade;
        this.tipoUnidade = tipoUnidade;
    }
    public UnidadeSaude(TiposUnidade tiposUnidade, Cidades cidades, String numeroCnes, String nomeDaUnidade, String tipoUnidade, Set departamentosTbs) {
       this.tiposUnidade = tiposUnidade;
       this.cidades = cidades;
       this.numeroCnes = numeroCnes;
       this.nomeDaUnidade = nomeDaUnidade;
       this.tipoUnidade = tipoUnidade;
       this.departamentosTbs = departamentosTbs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TiposUnidade getTiposUnidade() {
        return this.tiposUnidade;
    }
    
    public void setTiposUnidade(TiposUnidade tiposUnidade) {
        this.tiposUnidade = tiposUnidade;
    }
    public Cidades getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Cidades cidades) {
        this.cidades = cidades;
    }
    public String getNumeroCnes() {
        return this.numeroCnes;
    }
    
    public void setNumeroCnes(String numeroCnes) {
        this.numeroCnes = numeroCnes;
    }
    public String getNomeDaUnidade() {
        return this.nomeDaUnidade;
    }
    
    public void setNomeDaUnidade(String nomeDaUnidade) {
        this.nomeDaUnidade = nomeDaUnidade;
    }
    public String getTipoUnidade() {
        return this.tipoUnidade;
    }
    
    public void setTipoUnidade(String tipoUnidade) {
        this.tipoUnidade = tipoUnidade;
    }
    public Set getDepartamentosTbs() {
        return this.departamentosTbs;
    }
    
    public void setDepartamentosTbs(Set departamentosTbs) {
        this.departamentosTbs = departamentosTbs;
    }

    @Override
    public void copyAttributesOf(UnidadeSaude copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


