package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * UnidadeNotificadoraDoAcidente generated by hbm2java
 */
public class UnidadeNotificadoraDoAcidente  extends IModel<UnidadeNotificadoraDoAcidente> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String unidadeNotificadora;

    public UnidadeNotificadoraDoAcidente() {
    }

    public UnidadeNotificadoraDoAcidente(String codigo, String unidadeNotificadora) {
       this.codigo = codigo;
       this.unidadeNotificadora = unidadeNotificadora;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getUnidadeNotificadora() {
        return this.unidadeNotificadora;
    }
    
    public void setUnidadeNotificadora(String unidadeNotificadora) {
        this.unidadeNotificadora = unidadeNotificadora;
    }

    @Override
    public void copyAttributesOf(UnidadeNotificadoraDoAcidente copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


