package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * UsoCapacete generated by hbm2java
 */
public class UsoCapacete  extends IModel<UsoCapacete> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String usoCapacete;

    public UsoCapacete() {
    }

    public UsoCapacete(String codigo, String usoCapacete) {
       this.codigo = codigo;
       this.usoCapacete = usoCapacete;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getUsoCapacete() {
        return this.usoCapacete;
    }
    
    public void setUsoCapacete(String usoCapacete) {
        this.usoCapacete = usoCapacete;
    }

    @Override
    public void copyAttributesOf(UsoCapacete copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


