package br.com.eagravos.mobile.modelos;
// Generated 02/06/2014 08:44:54 by Hibernate Tools 3.6.0

import br.com.eagravos.mobile.interfaces.IModel;




/**
 * UsoCelular generated by hbm2java
 */
public class UsoCelular  extends IModel<UsoCelular> implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String usoCelular;

    public UsoCelular() {
    }

    public UsoCelular(String codigo, String usoCelular) {
       this.codigo = codigo;
       this.usoCelular = usoCelular;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getUsoCelular() {
        return this.usoCelular;
    }
    
    public void setUsoCelular(String usoCelular) {
        this.usoCelular = usoCelular;
    }

    @Override
    public void copyAttributesOf(UsoCelular copy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void unsetAttributes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cleanStringWithNull() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String label() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


